services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # App
      APP_NAME: "homework-real-time"
      APP_VERSION: "1.0.0"
      # Logger
      LOG_LEVEL: "debug"
      # Redis
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      # HTTP
      HTTP_PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      app_network:
        aliases:
          - app.lvh.me

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      app_network:
        aliases:
          - redis.lvh.me

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      app_network:
        aliases:
          - redisinsight.lvh.me

networks:
  app_network:
    external: false
