x-kafka-variables: &x-kafka-variables
  KAFKA_BROKER_ID: 1
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: 1
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29092"
  KAFKA_LISTENERS: CONTROLLER://kafka:29092,PLAINTEXT://kafka:9092
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

services:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      <<: *x-kafka-variables
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      app_network:
        aliases:
          - kafka.lvh.me

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8083:8080"
    networks:
      app_network:
        aliases:
          - kafka-ui.lvh.me

networks:
  app_network:
    external: false
