// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/SHshzik/homework_real_time/pkg/subscriber"
	"sync"
)

// Ensure, that HandlerMock does implement subscriber.Handler.
// If this is not the case, regenerate this file with moq.
var _ subscriber.Handler = &HandlerMock{}

// HandlerMock is a mock implementation of subscriber.Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked subscriber.Handler
//		mockedHandler := &HandlerMock{
//			CallFunc: func(ctx context.Context, message string) error {
//				panic("mock out the Call method")
//			},
//		}
//
//		// use mockedHandler in code that requires subscriber.Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// CallFunc mocks the Call method.
	CallFunc func(ctx context.Context, message string) error

	// calls tracks calls to the methods.
	calls struct {
		// Call holds details about calls to the Call method.
		Call []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message string
		}
	}
	lockCall sync.RWMutex
}

// Call calls CallFunc.
func (mock *HandlerMock) Call(ctx context.Context, message string) error {
	callInfo := struct {
		Ctx     context.Context
		Message string
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockCall.Lock()
	mock.calls.Call = append(mock.calls.Call, callInfo)
	mock.lockCall.Unlock()
	if mock.CallFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CallFunc(ctx, message)
}

// CallCalls gets all the calls that were made to Call.
// Check the length with:
//
//	len(mockedHandler.CallCalls())
func (mock *HandlerMock) CallCalls() []struct {
	Ctx     context.Context
	Message string
} {
	var calls []struct {
		Ctx     context.Context
		Message string
	}
	mock.lockCall.RLock()
	calls = mock.calls.Call
	mock.lockCall.RUnlock()
	return calls
}
