// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/SHshzik/homework_real_time/pkg/subscriber"
	rds "github.com/redis/go-redis/v9"
	"sync"
)

// Ensure, that RepositoryMock does implement subscriber.Repository.
// If this is not the case, regenerate this file with moq.
var _ subscriber.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of subscriber.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked subscriber.Repository
//		mockedRepository := &RepositoryMock{
//			SubscribeFunc: func(ctx context.Context, sType string) *rds.PubSub {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedRepository in code that requires subscriber.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, sType string) *rds.PubSub

	// calls tracks calls to the methods.
	calls struct {
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SType is the sType argument value.
			SType string
		}
	}
	lockSubscribe sync.RWMutex
}

// Subscribe calls SubscribeFunc.
func (mock *RepositoryMock) Subscribe(ctx context.Context, sType string) *rds.PubSub {
	callInfo := struct {
		Ctx   context.Context
		SType string
	}{
		Ctx:   ctx,
		SType: sType,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	if mock.SubscribeFunc == nil {
		var (
			pubSubOut *rds.PubSub
		)
		return pubSubOut
	}
	return mock.SubscribeFunc(ctx, sType)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedRepository.SubscribeCalls())
func (mock *RepositoryMock) SubscribeCalls() []struct {
	Ctx   context.Context
	SType string
} {
	var calls []struct {
		Ctx   context.Context
		SType string
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
