// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/SHshzik/homework_real_time/applications/subscriptions"
	"github.com/SHshzik/homework_real_time/applications/subscriptions/domain"
	"sync"
)

// Ensure, that ServiceMock does implement subscriptions.Service.
// If this is not the case, regenerate this file with moq.
var _ subscriptions.Service = &ServiceMock{}

// ServiceMock is a mock implementation of subscriptions.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked subscriptions.Service
//		mockedService := &ServiceMock{
//			SubscribeFunc: func(ctx context.Context, subscription *domain.Subscription) error {
//				panic("mock out the Subscribe method")
//			},
//			UnsubscribeFunc: func(ctx context.Context, subscription *domain.Subscription) error {
//				panic("mock out the Unsubscribe method")
//			},
//		}
//
//		// use mockedService in code that requires subscriptions.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, subscription *domain.Subscription) error

	// UnsubscribeFunc mocks the Unsubscribe method.
	UnsubscribeFunc func(ctx context.Context, subscription *domain.Subscription) error

	// calls tracks calls to the methods.
	calls struct {
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subscription is the subscription argument value.
			Subscription *domain.Subscription
		}
		// Unsubscribe holds details about calls to the Unsubscribe method.
		Unsubscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subscription is the subscription argument value.
			Subscription *domain.Subscription
		}
	}
	lockSubscribe   sync.RWMutex
	lockUnsubscribe sync.RWMutex
}

// Subscribe calls SubscribeFunc.
func (mock *ServiceMock) Subscribe(ctx context.Context, subscription *domain.Subscription) error {
	callInfo := struct {
		Ctx          context.Context
		Subscription *domain.Subscription
	}{
		Ctx:          ctx,
		Subscription: subscription,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	if mock.SubscribeFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SubscribeFunc(ctx, subscription)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedService.SubscribeCalls())
func (mock *ServiceMock) SubscribeCalls() []struct {
	Ctx          context.Context
	Subscription *domain.Subscription
} {
	var calls []struct {
		Ctx          context.Context
		Subscription *domain.Subscription
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// Unsubscribe calls UnsubscribeFunc.
func (mock *ServiceMock) Unsubscribe(ctx context.Context, subscription *domain.Subscription) error {
	callInfo := struct {
		Ctx          context.Context
		Subscription *domain.Subscription
	}{
		Ctx:          ctx,
		Subscription: subscription,
	}
	mock.lockUnsubscribe.Lock()
	mock.calls.Unsubscribe = append(mock.calls.Unsubscribe, callInfo)
	mock.lockUnsubscribe.Unlock()
	if mock.UnsubscribeFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UnsubscribeFunc(ctx, subscription)
}

// UnsubscribeCalls gets all the calls that were made to Unsubscribe.
// Check the length with:
//
//	len(mockedService.UnsubscribeCalls())
func (mock *ServiceMock) UnsubscribeCalls() []struct {
	Ctx          context.Context
	Subscription *domain.Subscription
} {
	var calls []struct {
		Ctx          context.Context
		Subscription *domain.Subscription
	}
	mock.lockUnsubscribe.RLock()
	calls = mock.calls.Unsubscribe
	mock.lockUnsubscribe.RUnlock()
	return calls
}
