// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/SHshzik/homework_real_time/applications/notifier/domain"
	"github.com/SHshzik/homework_real_time/applications/notifier/interfaces"
	"sync"
)

// Ensure, that SubscriptionRepositoryMock does implement interfaces.SubscriptionRepository.
// If this is not the case, regenerate this file with moq.
var _ interfaces.SubscriptionRepository = &SubscriptionRepositoryMock{}

// SubscriptionRepositoryMock is a mock implementation of interfaces.SubscriptionRepository.
//
//	func TestSomethingThatUsesSubscriptionRepository(t *testing.T) {
//
//		// make and configure a mocked interfaces.SubscriptionRepository
//		mockedSubscriptionRepository := &SubscriptionRepositoryMock{
//			FetchSubscriptionsFunc: func(ctx context.Context, subscriptionType domain.SubscriptionType) []string {
//				panic("mock out the FetchSubscriptions method")
//			},
//		}
//
//		// use mockedSubscriptionRepository in code that requires interfaces.SubscriptionRepository
//		// and then make assertions.
//
//	}
type SubscriptionRepositoryMock struct {
	// FetchSubscriptionsFunc mocks the FetchSubscriptions method.
	FetchSubscriptionsFunc func(ctx context.Context, subscriptionType domain.SubscriptionType) []string

	// calls tracks calls to the methods.
	calls struct {
		// FetchSubscriptions holds details about calls to the FetchSubscriptions method.
		FetchSubscriptions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SubscriptionType is the subscriptionType argument value.
			SubscriptionType domain.SubscriptionType
		}
	}
	lockFetchSubscriptions sync.RWMutex
}

// FetchSubscriptions calls FetchSubscriptionsFunc.
func (mock *SubscriptionRepositoryMock) FetchSubscriptions(ctx context.Context, subscriptionType domain.SubscriptionType) []string {
	callInfo := struct {
		Ctx              context.Context
		SubscriptionType domain.SubscriptionType
	}{
		Ctx:              ctx,
		SubscriptionType: subscriptionType,
	}
	mock.lockFetchSubscriptions.Lock()
	mock.calls.FetchSubscriptions = append(mock.calls.FetchSubscriptions, callInfo)
	mock.lockFetchSubscriptions.Unlock()
	if mock.FetchSubscriptionsFunc == nil {
		var (
			stringsOut []string
		)
		return stringsOut
	}
	return mock.FetchSubscriptionsFunc(ctx, subscriptionType)
}

// FetchSubscriptionsCalls gets all the calls that were made to FetchSubscriptions.
// Check the length with:
//
//	len(mockedSubscriptionRepository.FetchSubscriptionsCalls())
func (mock *SubscriptionRepositoryMock) FetchSubscriptionsCalls() []struct {
	Ctx              context.Context
	SubscriptionType domain.SubscriptionType
} {
	var calls []struct {
		Ctx              context.Context
		SubscriptionType domain.SubscriptionType
	}
	mock.lockFetchSubscriptions.RLock()
	calls = mock.calls.FetchSubscriptions
	mock.lockFetchSubscriptions.RUnlock()
	return calls
}
