// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/SHshzik/homework_real_time/applications/subscriptions/interfaces"
	"sync"
)

// Ensure, that SubscriptionRepositoryMock does implement interfaces.SubscriptionRepository.
// If this is not the case, regenerate this file with moq.
var _ interfaces.SubscriptionRepository = &SubscriptionRepositoryMock{}

// SubscriptionRepositoryMock is a mock implementation of interfaces.SubscriptionRepository.
//
//	func TestSomethingThatUsesSubscriptionRepository(t *testing.T) {
//
//		// make and configure a mocked interfaces.SubscriptionRepository
//		mockedSubscriptionRepository := &SubscriptionRepositoryMock{
//			AddSubscriptionFunc: func(ctx context.Context, sType string, userID string)  {
//				panic("mock out the AddSubscription method")
//			},
//			RemoveSubscriptionFunc: func(ctx context.Context, sType string, userID string)  {
//				panic("mock out the RemoveSubscription method")
//			},
//		}
//
//		// use mockedSubscriptionRepository in code that requires interfaces.SubscriptionRepository
//		// and then make assertions.
//
//	}
type SubscriptionRepositoryMock struct {
	// AddSubscriptionFunc mocks the AddSubscription method.
	AddSubscriptionFunc func(ctx context.Context, sType string, userID string)

	// RemoveSubscriptionFunc mocks the RemoveSubscription method.
	RemoveSubscriptionFunc func(ctx context.Context, sType string, userID string)

	// calls tracks calls to the methods.
	calls struct {
		// AddSubscription holds details about calls to the AddSubscription method.
		AddSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SType is the sType argument value.
			SType string
			// UserID is the userID argument value.
			UserID string
		}
		// RemoveSubscription holds details about calls to the RemoveSubscription method.
		RemoveSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SType is the sType argument value.
			SType string
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockAddSubscription    sync.RWMutex
	lockRemoveSubscription sync.RWMutex
}

// AddSubscription calls AddSubscriptionFunc.
func (mock *SubscriptionRepositoryMock) AddSubscription(ctx context.Context, sType string, userID string) {
	callInfo := struct {
		Ctx    context.Context
		SType  string
		UserID string
	}{
		Ctx:    ctx,
		SType:  sType,
		UserID: userID,
	}
	mock.lockAddSubscription.Lock()
	mock.calls.AddSubscription = append(mock.calls.AddSubscription, callInfo)
	mock.lockAddSubscription.Unlock()
	if mock.AddSubscriptionFunc == nil {
		return
	}
	mock.AddSubscriptionFunc(ctx, sType, userID)
}

// AddSubscriptionCalls gets all the calls that were made to AddSubscription.
// Check the length with:
//
//	len(mockedSubscriptionRepository.AddSubscriptionCalls())
func (mock *SubscriptionRepositoryMock) AddSubscriptionCalls() []struct {
	Ctx    context.Context
	SType  string
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		SType  string
		UserID string
	}
	mock.lockAddSubscription.RLock()
	calls = mock.calls.AddSubscription
	mock.lockAddSubscription.RUnlock()
	return calls
}

// RemoveSubscription calls RemoveSubscriptionFunc.
func (mock *SubscriptionRepositoryMock) RemoveSubscription(ctx context.Context, sType string, userID string) {
	callInfo := struct {
		Ctx    context.Context
		SType  string
		UserID string
	}{
		Ctx:    ctx,
		SType:  sType,
		UserID: userID,
	}
	mock.lockRemoveSubscription.Lock()
	mock.calls.RemoveSubscription = append(mock.calls.RemoveSubscription, callInfo)
	mock.lockRemoveSubscription.Unlock()
	if mock.RemoveSubscriptionFunc == nil {
		return
	}
	mock.RemoveSubscriptionFunc(ctx, sType, userID)
}

// RemoveSubscriptionCalls gets all the calls that were made to RemoveSubscription.
// Check the length with:
//
//	len(mockedSubscriptionRepository.RemoveSubscriptionCalls())
func (mock *SubscriptionRepositoryMock) RemoveSubscriptionCalls() []struct {
	Ctx    context.Context
	SType  string
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		SType  string
		UserID string
	}
	mock.lockRemoveSubscription.RLock()
	calls = mock.calls.RemoveSubscription
	mock.lockRemoveSubscription.RUnlock()
	return calls
}
